// src/pages/Inventory/CreateInventory.tsx

import React, { useState, useEffect, useCallback, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import { createInventory } from '../../services/api';
import { Inventory } from '../../types';
import Loading from '../../components/Loading';
import { Package, FileText, ChevronDown, ChevronUp, ArrowLeft } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { notify } from '../../utils/notifications';
import { validateZone, validateRequiredField } from '../../utils/validation';
import { handleApiError, formatApiValidationErrors, logError } from '../../utils/errorHandling';
import { useCollapsibleSections, CollapsibleSection } from '../../hooks/useCollapsibleSections';
import { MAX_FIELD_LENGTH, ACTION_MESSAGES, PLACEHOLDERS } from '../../constants/inventory';
import { generateSKU } from '../../utils/sku';

const LOCAL_PATH_PREFIX = window.location.hostname === 'localhost' ? '/staff/' : '/';

interface FormErrors {
    [key: string]: string | undefined;
}

const CreateInventory: React.FC = () => {
    const navigate = useNavigate();

    const [formData, setFormData] = useState<Inventory>({
        name: '',
        sku: '',
        type: '',
        status: 'active',
        zone: undefined,
        product_id: undefined,
        description: '',
    });
    const [errors, setErrors] = useState<FormErrors>({});
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [isSkuManuallyEdited, setIsSkuManuallyEdited] = useState(false);
    const { sections, toggleSection } = useCollapsibleSections([
        { id: 'basic', title: 'Basic Information', icon: Package, isOpen: true },
        { id: 'description', title: 'Description', icon: FileText, isOpen: true },
    ]);
    
    useEffect(() => {
        if (!isSkuManuallyEdited && formData.name) {
            const autoGeneratedSku = generateSKU(formData.name);
            setFormData((prevData) => ({
                ...prevData,
                sku: autoGeneratedSku
            }));
        } else if (!isSkuManuallyEdited && !formData.name) {
            setFormData((prevData) => ({
                ...prevData,
                sku: ''
            }));
        }
    }, [formData.name, isSkuManuallyEdited]);

    useEffect(() => {
        document.title = "Create Inventory | RenoXpert";
    }, []);


    const handleBackClick = useCallback(() => {
        navigate(LOCAL_PATH_PREFIX + 'inventory');
    }, [navigate]);


    const handleZoneChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const { value } = e.target;
        
        const upperValue = value.toUpperCase();
        const zoneRegex = /^[A-Z]?$/;
        
        if (upperValue === '' || zoneRegex.test(upperValue)) {
            setFormData((prevData) => ({
                ...prevData,
                zone: upperValue || undefined
            }));
            if (errors.zone) {
                setErrors((prevErrors) => ({
                    ...prevErrors,
                    zone: undefined
                }));
            }
        } else {
            const zoneError = validateZone(upperValue);
            if (zoneError) {
                setErrors((prevErrors) => ({
                    ...prevErrors,
                    zone: zoneError
                }));
            }
        }
    }, [errors.zone]);

    const handleZoneKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
        const { key } = e;
        
        // Allow: backspace, delete, tab, escape, enter, and arrow keys
        const allowedKeys = ['Backspace', 'Delete', 'Tab', 'Escape', 'Enter', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End'];
        
        // Allow control keys
        if (allowedKeys.includes(key) || e.ctrlKey || e.metaKey) {
            return;
        }
        
        if (key.length === 1 && /^[A-Za-z]$/.test(key)) {
            return;
        }
        
        e.preventDefault();
    }, []);

    const handleZonePaste = useCallback((e: React.ClipboardEvent<HTMLInputElement>) => {
        e.preventDefault();
        const pastedText = e.clipboardData.getData('text').toUpperCase().replace(/[^A-Z]/g, '').slice(0, 1);
        if (pastedText) {
            setFormData((prevData) => ({
                ...prevData,
                zone: pastedText
            }));
            if (errors.zone) {
                setErrors((prevErrors) => ({
                    ...prevErrors,
                    zone: undefined
                }));
            }
        }
    }, [errors.zone]);

    const handleSKUChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const { value } = e.target;
        
        const processedValue = value.toUpperCase().replace(/[^A-Z0-9-]/g, '');
        
        setFormData((prevData) => ({
            ...prevData,
            sku: processedValue
        }));
        
        if (processedValue !== '') {
            setIsSkuManuallyEdited(true);
        }
        
        if (errors.sku) {
            setErrors((prevErrors) => ({
                ...prevErrors,
                sku: undefined
            }));
        }
    }, [errors.sku]);

    const handleSKUBlur = useCallback(() => {
        if (!formData.sku || formData.sku.trim() === '') {
            setIsSkuManuallyEdited(false);
        }
    }, [formData.sku]);

    const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;
        
        if (name === 'sku') {
            handleSKUChange(e as React.ChangeEvent<HTMLInputElement>);
            return;
        }
        
        setFormData((prevData) => ({
                ...prevData,
                [name]: value
        }));
        
        if (errors[name]) {
            setErrors((prevErrors) => ({
                ...prevErrors,
                [name]: undefined
            }));
        }
    }, [errors, handleSKUChange]);

    const validate = useCallback((): FormErrors => {
        const newErrors: FormErrors = {};

        const nameError = validateRequiredField(formData.name, 'Item name', 255);
        if (nameError) {
            newErrors.name = nameError;
        }

        if (formData.description && formData.description.length > MAX_FIELD_LENGTH.DESCRIPTION) {
            newErrors.description = `Description must not exceed ${MAX_FIELD_LENGTH.DESCRIPTION} characters`;
        }

        if (formData.type && formData.type.length > MAX_FIELD_LENGTH.TYPE) {
            newErrors.type = `Type must not exceed ${MAX_FIELD_LENGTH.TYPE} characters`;
        }

        if (formData.status && formData.status.length > MAX_FIELD_LENGTH.STATUS) {
            newErrors.status = `Status must not exceed ${MAX_FIELD_LENGTH.STATUS} characters`;
        }

        const zoneError = validateZone(formData.zone);
        if (zoneError) {
            newErrors.zone = zoneError;
        }

        if (formData.sku && formData.sku.trim() !== '') {
            const skuRegex = /^[A-Z0-9-]+$/;
            if (!skuRegex.test(formData.sku)) {
                newErrors.sku = 'SKU can only contain uppercase letters, numbers, and hyphens';
            }
            if (formData.sku.length > 255) {
                newErrors.sku = 'SKU must not exceed 255 characters';
            }
        }

        return newErrors;
    }, [formData]);

    const handleSubmit = useCallback(async () => {
        setErrors({});
        const validationErrors = validate();

        if (Object.keys(validationErrors).length > 0) {
            setErrors(validationErrors);
            notify('error', 'Please fix the validation errors');
            return;
        }

        setIsSubmitting(true);

        try {
            // Exclude alert_level from the payload
            // Also exclude sku if it's empty (backend will auto-generate)
            // Set description to null if empty (backend accepts nullable)
            const { alert_level, ...payloadData } = formData;
            if (!payloadData.sku || payloadData.sku.trim() === '') {
                delete payloadData.sku;
            }
            if (!payloadData.description || payloadData.description.trim() === '') {
                payloadData.description = null;
            }
            const response = await createInventory(payloadData);

            if (response?.success) {
                notify('success', 'Inventory item created successfully');
                // Navigate to the newly created inventory item detail page
                navigate(LOCAL_PATH_PREFIX + 'inventory/' + response.data.id);
            } else {
                notify('error', response?.message || 'Failed to create inventory item');
            }
        } catch (error: unknown) {
            logError('creating inventory', error);
            const formattedErrors = formatApiValidationErrors(error);
            if (Object.keys(formattedErrors).length > 0) {
                setErrors(formattedErrors);
            }
            notify('error', handleApiError(error, 'Failed to create inventory item'));
        } finally {
            setIsSubmitting(false);
        }
    }, [formData, validate, notify, navigate]);

    const SectionHeader = React.memo(({ section }: { section: CollapsibleSection }) => {
        const Icon = section.icon;
        return (
            <button
                type="button"
                onClick={() => toggleSection(section.id)}
                className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors rounded-t-lg border-b border-gray-200"
            >
                <div className="flex items-center gap-3">
                    <Icon className="w-5 h-5 text-gray-600" />
                    <h3 className="text-base font-semibold text-gray-900">{section.title}</h3>
                </div>
                {section.isOpen ? (
                    <ChevronUp className="w-5 h-5 text-gray-500" />
                ) : (
                    <ChevronDown className="w-5 h-5 text-gray-500" />
                )}
            </button>
        );
    });

    return (
        <>
            {isSubmitting && <Loading />}

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6" style={{ fontFamily: 'Inter, sans-serif' }}>
                {/* Page Header */}
                <div className="mb-6">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={handleBackClick}
                            className="btn btn-sm btn-light hover:bg-gray-100 transition-colors"
                            disabled={isSubmitting}
                        >
                            <ArrowLeft className="w-4 h-4" />
                        </button>
                        <h1 className="text-3xl font-bold text-slate-900">Create Inventory Item</h1>
                    </div>
                </div>

                {/* Form Card */}
                <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                    {/* Form Content */}
                    <div className="p-6">
                        <div className="flex flex-col gap-4">
                            {/* Basic Information Section */}
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.2 }}
                                className="bg-gray-50 rounded-lg border border-gray-200 overflow-hidden"
                            >
                                <SectionHeader section={sections[0]} />
                                <AnimatePresence>
                                    {sections[0].isOpen && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: 'auto', opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.2 }}
                                            className="p-4"
                                        >
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Item Name <span className="text-red-500">*</span>
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="name"
                                                        value={formData.name || ''}
                                                        onChange={handleChange}
                                                        className={`input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${errors.name ? 'border-red-500' : ''}`}
                                                        placeholder="Enter item name"
                                                        maxLength={255}
                                                        disabled={isSubmitting}
                                                    />
                                                    {errors.name && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.name}</span>
                                                    )}
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Type
                                                    </label>
                                                    <select
                                                        name="type"
                                                        value={formData.type || ''}
                                                        onChange={handleChange}
                                                        className="select w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all"
                                                        disabled={isSubmitting}
                                                    >
                                                        <option value="">Select type (optional)</option>
                                                        <option value="Carpentry">Carpentry</option>
                                                        <option value="Electrical Appliances">Electrical Appliances</option>
                                                        <option value="Furniture IoT / Smart devices">Furniture IoT / Smart devices</option>
                                                        <option value="Loose Items / Furnishing and room equipment">Loose Items / Furnishing and room equipment</option>
                                                        <option value="Project Management">Project Management</option>
                                                        <option value="Renovation">Renovation</option>
                                                        <option value="Electrical component">Electrical component</option>
                                                        <option value="Security and surveillance">Security and surveillance</option>
                                                        <option value="Safety equipment">Safety equipment</option>
                                                    </select>
                                                    {errors.type && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.type}</span>
                                                    )}
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Status
                                                    </label>
                                                    <select
                                                        name="status"
                                                        value={formData.status || 'active'}
                                                        onChange={handleChange}
                                                        className="select w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all"
                                                        disabled={isSubmitting}
                                                    >
                                                        <option value="active">Active</option>
                                                        <option value="inactive">Inactive</option>
                                                    </select>
                                                    {errors.status && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.status}</span>
                                                    )}
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Zone
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="zone"
                                                        value={formData.zone || ''}
                                                        onChange={handleZoneChange}
                                                        onKeyDown={handleZoneKeyDown}
                                                        onPaste={handleZonePaste}
                                                        className={`input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${errors.zone ? 'border-red-500' : ''}`}
                                                        placeholder="Enter zone (A-Z)"
                                                        maxLength={1}
                                                        disabled={isSubmitting}
                                                    />
                                                    {errors.zone && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.zone}</span>
                                                    )}
                                                    <p className="text-xs text-gray-500 mt-1">Single uppercase letter (A-Z)</p>
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        SKU
                                                        {!isSkuManuallyEdited && formData.name && (
                                                            <span className="ml-2 text-xs text-gray-500 font-normal">(Auto-generated)</span>
                                                        )}
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="sku"
                                                        value={formData.sku || ''}
                                                        onChange={handleChange}
                                                        onBlur={handleSKUBlur}
                                                        className={`input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${
                                                            errors.sku ? 'border-red-500' : 
                                                            !isSkuManuallyEdited && formData.name ? 'border-blue-200 bg-blue-50/30' : ''
                                                        }`}
                                                        placeholder="Auto-generated from name if empty"
                                                        maxLength={255}
                                                        disabled={isSubmitting}
                                                    />
                                                    {errors.sku && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.sku}</span>
                                                    )}
                                                    <p className="text-xs text-gray-500 mt-1">Uppercase letters, numbers, and hyphens only</p>
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Product ID
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="product_id"
                                                        value={formData.product_id || ''}
                                                        onChange={handleChange}
                                                        className="input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all"
                                                        placeholder="Enter product ID (optional)"
                                                        disabled={isSubmitting}
                                                    />
                                                </div>
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>

                            {/* Description Section */}
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.2, delay: 0.05 }}
                                className="bg-gray-50 rounded-lg border border-gray-200 overflow-hidden"
                            >
                                <SectionHeader section={sections[1]} />
                                <AnimatePresence>
                                    {sections[1].isOpen && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: 'auto', opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.2 }}
                                            className="p-4"
                                        >
                                            <textarea
                                                name="description"
                                                value={formData.description || ''}
                                                onChange={handleChange}
                                                className={`textarea w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${errors.description ? 'border-red-500' : ''}`}
                                                placeholder="Enter description (optional)"
                                                rows={4}
                                                maxLength={255}
                                                disabled={isSubmitting}
                                            />
                                            {errors.description && (
                                                <span className="text-red-500 text-sm mt-1 block">{errors.description}</span>
                                            )}
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>
                        </div>
                    </div>

                    {/* Form Footer */}
                    <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex justify-end gap-3">
                        <button
                            className="btn btn-light border border-gray-300 hover:bg-gray-50 transition-colors"
                            onClick={handleBackClick}
                            disabled={isSubmitting}
                        >
                            Cancel
                        </button>
                        <button
                            className="btn btn-primary hover:bg-primary-dark transition-colors"
                            onClick={handleSubmit}
                            disabled={isSubmitting}
                        >
                            {isSubmitting ? ACTION_MESSAGES.CREATING : 'Create Inventory Item'}
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default CreateInventory;
