// src/pages/Inventory/EditInventory.tsx

import React, { useState, useEffect, useCallback } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { updateInventory } from '../../services/api';
import { Inventory } from '../../types';
import Loading from '../../components/Loading';
import useFetchInventory from '../../hook/useFetchInventory';
import { Package, FileText, ChevronDown, ChevronUp, ArrowLeft } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { notify } from '../../utils/notifications';
import { validateZone, validateRequiredField } from '../../utils/validation';
import { handleApiError, formatApiValidationErrors, logError } from '../../utils/errorHandling';
import { useCollapsibleSections } from '../../hooks/useCollapsibleSections';
import { MODAL_CLOSE_DELAY, MAX_FIELD_LENGTH } from '../../constants/inventory';
import { generateSKU } from '../../utils/sku';

const LOCAL_PATH_PREFIX = window.location.hostname === 'localhost' ? '/staff/' : '/';

interface FormErrors {
    [key: string]: string | undefined;
}

interface CollapsibleSection {
    id: string;
    title: string;
    icon: React.ElementType;
    isOpen: boolean;
}

const EditInventory: React.FC = () => {
    const navigate = useNavigate();
    const { id } = useParams<{ id: string }>();
    const inventoryItemId = id ? parseInt(id, 10) : null;

    // Fetch inventory item data
    const { inventory, loading: inventoryLoading, error: inventoryError, refetch } = useFetchInventory(inventoryItemId);

    // Form state
    const [formData, setFormData] = useState<Inventory>({} as Inventory);
    const [errors, setErrors] = useState<FormErrors>({});
    const [isSubmitting, setIsSubmitting] = useState(false);
    const [isSkuManuallyEdited, setIsSkuManuallyEdited] = useState(false);
    const { sections, toggleSection } = useCollapsibleSections([
        { id: 'basic', title: 'Basic Information', icon: Package, isOpen: true },
        { id: 'description', title: 'Description', icon: FileText, isOpen: true },
    ]);

    // Set document title
    useEffect(() => {
        document.title = "Edit Inventory | RenoXpert";
    }, []);

    // Pre-fill form data when inventory is loaded
    useEffect(() => {
        if (inventory && inventory.id) {
            const inventoryName = inventory.name || '';
            const inventorySku = inventory.sku || '';
            const autoGeneratedSku = generateSKU(inventoryName);
            
            setFormData({
                ...inventory,
                description: inventory.description || '',
            });
            // If existing SKU matches auto-generated SKU, allow auto-update when name changes
            // Otherwise, preserve the manually set SKU
            setIsSkuManuallyEdited(inventorySku !== '' && inventorySku !== autoGeneratedSku);
            setErrors({});
        }
    }, [inventory]);

    // Auto-generate SKU from name in real-time as user types
    useEffect(() => {
        // Real-time SKU generation when name changes (if not manually edited)
        if (!isSkuManuallyEdited && formData.name) {
            const autoGeneratedSku = generateSKU(formData.name);
            setFormData((prevData) => ({
                ...prevData,
                sku: autoGeneratedSku
            }));
        } else if (!isSkuManuallyEdited && !formData.name) {
            // Clear SKU if name is cleared and SKU wasn't manually edited
            setFormData((prevData) => ({
                ...prevData,
                sku: ''
            }));
        }
    }, [formData.name, isSkuManuallyEdited]);


    // Navigation handlers
    const handleBackClick = useCallback(() => {
        navigate(LOCAL_PATH_PREFIX + 'inventory/' + inventoryItemId);
    }, [navigate, inventoryItemId]);


    // Zone field handlers
    const handleZoneChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const { value } = e.target;
        
        // Convert to uppercase immediately
        const upperValue = value.toUpperCase();
        
        // Only allow A-Z (single character)
        const zoneRegex = /^[A-Z]?$/;
        
        if (upperValue === '' || zoneRegex.test(upperValue)) {
            // Valid input - update form data
            setFormData((prevData) => ({
                ...prevData,
                zone: upperValue || undefined
            }));
            // Clear error if valid
            if (errors.zone) {
                setErrors((prevErrors) => ({
                    ...prevErrors,
                    zone: undefined
                }));
            }
        } else {
            // Invalid input - show error but don't update value
            const zoneError = validateZone(upperValue);
            if (zoneError) {
                setErrors((prevErrors) => ({
                    ...prevErrors,
                    zone: zoneError
                }));
            }
        }
    }, [errors.zone]);

    const handleZoneKeyDown = useCallback((e: React.KeyboardEvent<HTMLInputElement>) => {
        const { key } = e;
        
        // Allow: backspace, delete, tab, escape, enter, and arrow keys
        const allowedKeys = ['Backspace', 'Delete', 'Tab', 'Escape', 'Enter', 'ArrowLeft', 'ArrowRight', 'ArrowUp', 'ArrowDown', 'Home', 'End'];
        
        // Allow control keys
        if (allowedKeys.includes(key) || e.ctrlKey || e.metaKey) {
            return;
        }
        
        // Allow A-Z (case-insensitive)
        if (key.length === 1 && /^[A-Za-z]$/.test(key)) {
            return;
        }
        
        // Block everything else
        e.preventDefault();
    }, []);

    const handleZonePaste = useCallback((e: React.ClipboardEvent<HTMLInputElement>) => {
        e.preventDefault();
        const pastedText = e.clipboardData.getData('text').toUpperCase().replace(/[^A-Z]/g, '').slice(0, 1);
        if (pastedText) {
            setFormData((prevData) => ({
                ...prevData,
                zone: pastedText
            }));
            // Clear error if valid
            if (errors.zone) {
                setErrors((prevErrors) => ({
                    ...prevErrors,
                    zone: undefined
                }));
            }
        }
    }, [errors.zone]);

    // SKU change handler (uppercase conversion and manual edit tracking)
    const handleSKUChange = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
        const { value } = e.target;
        
        // Convert to uppercase and only allow A-Z, 0-9, and hyphens
        const processedValue = value.toUpperCase().replace(/[^A-Z0-9-]/g, '');
        
        setFormData((prevData) => ({
            ...prevData,
            sku: processedValue
        }));
        
        // Mark as manually edited if user types something
        if (processedValue !== '') {
            setIsSkuManuallyEdited(true);
        }
        
        if (errors.sku) {
            setErrors((prevErrors) => ({
                ...prevErrors,
                sku: undefined
            }));
        }
    }, [errors.sku]);

    // Handle SKU blur - resume auto-generation if field is cleared
    const handleSKUBlur = useCallback(() => {
        if (!formData.sku || formData.sku.trim() === '') {
            setIsSkuManuallyEdited(false);
        }
    }, [formData.sku]);

    // General form change handler
    const handleChange = useCallback((e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement | HTMLTextAreaElement>) => {
        const { name, value } = e.target;
        
        // Handle SKU separately
        if (name === 'sku') {
            handleSKUChange(e as React.ChangeEvent<HTMLInputElement>);
            return;
        }
        
        setFormData((prevData) => ({
                ...prevData,
                [name]: value
        }));
        
        if (errors[name]) {
            setErrors((prevErrors) => ({
                ...prevErrors,
                [name]: undefined
            }));
        }
    }, [errors, handleSKUChange]);

    // Form validation
    const validate = useCallback((): FormErrors => {
        const newErrors: FormErrors = {};

        // Validate required fields
        const nameError = validateRequiredField(formData.name, 'Item name', 255);
        if (nameError) {
            newErrors.name = nameError;
        }

        // Validate optional fields max length
        if (formData.description && formData.description.length > MAX_FIELD_LENGTH.DESCRIPTION) {
            newErrors.description = `Description must not exceed ${MAX_FIELD_LENGTH.DESCRIPTION} characters`;
        }

        if (formData.type && formData.type.length > MAX_FIELD_LENGTH.TYPE) {
            newErrors.type = `Type must not exceed ${MAX_FIELD_LENGTH.TYPE} characters`;
        }

        if (formData.status && formData.status.length > MAX_FIELD_LENGTH.STATUS) {
            newErrors.status = `Status must not exceed ${MAX_FIELD_LENGTH.STATUS} characters`;
        }

        // Validate zone
        const zoneError = validateZone(formData.zone);
        if (zoneError) {
            newErrors.zone = zoneError;
        }

        // Validate SKU format if provided
        if (formData.sku && formData.sku.trim() !== '') {
            const skuRegex = /^[A-Z0-9-]+$/;
            if (!skuRegex.test(formData.sku)) {
                newErrors.sku = 'SKU can only contain uppercase letters, numbers, and hyphens';
            }
            if (formData.sku.length > 255) {
                newErrors.sku = 'SKU must not exceed 255 characters';
            }
        }

        return newErrors;
    }, [formData]);

    // Form submission
    const handleSubmit = useCallback(async () => {
        if (!formData.id || !inventoryItemId) return;

        setErrors({});
        const validationErrors = validate();

        if (Object.keys(validationErrors).length > 0) {
            setErrors(validationErrors);
            notify('error', 'Please fix the validation errors');
            return;
        }

        setIsSubmitting(true);

        try {
            // Set description to null if empty (backend accepts nullable)
            // Always include SKU in payload (backend will auto-generate if empty/null)
            const payloadData = { ...formData, id: inventoryItemId };
            if (!payloadData.description || payloadData.description.trim() === '') {
                payloadData.description = null;
            }
            // Ensure SKU is included in payload (will be empty string if not set, backend handles auto-generation)
            payloadData.sku = payloadData.sku || '';
            const response = await updateInventory(payloadData);

            if (response?.success) {
                notify('success', 'Inventory item updated successfully');
                // Refetch inventory data to get updated values
                refetch();
                // Navigate back to detail page after a short delay
                setTimeout(() => {
                    navigate(LOCAL_PATH_PREFIX + 'inventory/' + inventoryItemId);
                }, MODAL_CLOSE_DELAY);
            } else {
                notify('error', response?.message || 'Failed to update inventory item');
            }
        } catch (error: unknown) {
            logError('updating inventory', error);
            const formattedErrors = formatApiValidationErrors(error);
            if (Object.keys(formattedErrors).length > 0) {
                setErrors(formattedErrors);
            }
            notify('error', handleApiError(error, 'Failed to update inventory item'));
        } finally {
            setIsSubmitting(false);
        }
    }, [formData, inventoryItemId, validate, notify, refetch, navigate]);

    // Section header component
    const SectionHeader = React.memo(({ section }: { section: CollapsibleSection }) => {
        const Icon = section.icon;
        return (
            <button
                type="button"
                onClick={() => toggleSection(section.id)}
                className="w-full flex items-center justify-between p-4 bg-gray-50 hover:bg-gray-100 transition-colors rounded-t-lg border-b border-gray-200"
            >
                <div className="flex items-center gap-3">
                    <Icon className="w-5 h-5 text-gray-600" />
                    <h3 className="text-base font-semibold text-gray-900">{section.title}</h3>
                </div>
                {section.isOpen ? (
                    <ChevronUp className="w-5 h-5 text-gray-500" />
                ) : (
                    <ChevronDown className="w-5 h-5 text-gray-500" />
                )}
            </button>
        );
    });

    // Loading state
    if (inventoryLoading) {
        return <Loading />;
    }

    // Error state
    if (inventoryError) {
        return (
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                <div className="bg-white rounded-xl border border-red-200 shadow-sm p-6">
                    <div className="text-red-600 mb-4">Failed to load inventory item: {inventoryError}</div>
                    <button
                        className="btn btn-primary"
                        onClick={handleBackClick}
                    >
                        Go Back
                    </button>
                </div>
            </div>
        );
    }

    // Not found state
    if (!inventory || !inventory.id) {
        return (
            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6">
                <div className="bg-white rounded-xl border border-gray-200 shadow-sm p-6">
                    <div className="text-gray-500 mb-4">Inventory item not found</div>
                    <button
                        className="btn btn-primary"
                        onClick={handleBackClick}
                    >
                        Go Back
                    </button>
                </div>
            </div>
        );
    }

    return (
        <>
            {isSubmitting && <Loading />}

            <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-6" style={{ fontFamily: 'Inter, sans-serif' }}>
                {/* Page Header */}
                <div className="mb-6">
                    <div className="flex items-center gap-4">
                        <button
                            onClick={handleBackClick}
                            className="btn btn-sm btn-light hover:bg-gray-100 transition-colors"
                            disabled={isSubmitting}
                        >
                            <ArrowLeft className="w-4 h-4" />
                        </button>
                        <h1 className="text-3xl font-bold text-slate-900">Edit Inventory Item</h1>
                    </div>
                </div>

                {/* Form Card */}
                <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden">
                    {/* Form Content */}
                    <div className="p-6">
                        <div className="flex flex-col gap-4">
                            {/* Basic Information Section */}
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.2 }}
                                className="bg-gray-50 rounded-lg border border-gray-200 overflow-hidden"
                            >
                                <SectionHeader section={sections[0]} />
                                <AnimatePresence>
                                    {sections[0].isOpen && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: 'auto', opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.2 }}
                                            className="p-4"
                                        >
                                            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Item Name <span className="text-red-500">*</span>
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="name"
                                                        value={formData.name || ''}
                                                        onChange={handleChange}
                                                        className={`input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${errors.name ? 'border-red-500' : ''}`}
                                                        placeholder="Enter item name"
                                                        maxLength={255}
                                                        disabled={isSubmitting}
                                                    />
                                                    {errors.name && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.name}</span>
                                                    )}
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Type
                                                    </label>
                                                    <select
                                                        name="type"
                                                        value={formData.type || ''}
                                                        onChange={handleChange}
                                                        className="select w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all"
                                                        disabled={isSubmitting}
                                                    >
                                                        <option value="">Select type (optional)</option>
                                                        <option value="Carpentry">Carpentry</option>
                                                        <option value="Electrical Appliances">Electrical Appliances</option>
                                                        <option value="Furniture IoT / Smart devices">Furniture IoT / Smart devices</option>
                                                        <option value="Loose Items / Furnishing and room equipment">Loose Items / Furnishing and room equipment</option>
                                                        <option value="Project Management">Project Management</option>
                                                        <option value="Renovation">Renovation</option>
                                                        <option value="Electrical component">Electrical component</option>
                                                        <option value="Security and surveillance">Security and surveillance</option>
                                                        <option value="Safety equipment">Safety equipment</option>
                                                    </select>
                                                    {errors.type && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.type}</span>
                                                    )}
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Status
                                                    </label>
                                                    <select
                                                        name="status"
                                                        value={formData.status || 'active'}
                                                        onChange={handleChange}
                                                        className="select w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all"
                                                        disabled={isSubmitting}
                                                    >
                                                        <option value="active">Active</option>
                                                        <option value="inactive">Inactive</option>
                                                    </select>
                                                    {errors.status && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.status}</span>
                                                    )}
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Zone
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="zone"
                                                        value={formData.zone || ''}
                                                        onChange={handleZoneChange}
                                                        onKeyDown={handleZoneKeyDown}
                                                        onPaste={handleZonePaste}
                                                        className={`input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${errors.zone ? 'border-red-500' : ''}`}
                                                        placeholder="Enter zone (A-Z)"
                                                        maxLength={1}
                                                        disabled={isSubmitting}
                                                    />
                                                    {errors.zone && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.zone}</span>
                                                    )}
                                                    <p className="text-xs text-gray-500 mt-1">Single uppercase letter (A-Z)</p>
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        SKU
                                                        {!isSkuManuallyEdited && formData.name && (
                                                            <span className="ml-2 text-xs text-gray-500 font-normal">(Auto-generated)</span>
                                                        )}
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="sku"
                                                        value={formData.sku || ''}
                                                        onChange={handleChange}
                                                        onBlur={handleSKUBlur}
                                                        className={`input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${
                                                            errors.sku ? 'border-red-500' : 
                                                            !isSkuManuallyEdited && formData.name ? 'border-blue-200 bg-blue-50/30' : ''
                                                        }`}
                                                        placeholder="Auto-generated from name if empty"
                                                        maxLength={255}
                                                        disabled={isSubmitting}
                                                    />
                                                    {errors.sku && (
                                                        <span className="text-red-500 text-sm mt-1 block">{errors.sku}</span>
                                                    )}
                                                    <p className="text-xs text-gray-500 mt-1">Uppercase letters, numbers, and hyphens only</p>
                                                </div>

                                                <div>
                                                    <label className="text-sm font-medium text-gray-700 mb-1 block">
                                                        Product ID
                                                    </label>
                                                    <input
                                                        type="text"
                                                        name="product_id"
                                                        value={formData.product_id || ''}
                                                        onChange={handleChange}
                                                        className="input w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all"
                                                        placeholder="Enter product ID (optional)"
                                                        disabled={isSubmitting}
                                                    />
                                                </div>
                                            </div>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>

                            {/* Description Section */}
                            <motion.div
                                initial={{ opacity: 0, y: 10 }}
                                animate={{ opacity: 1, y: 0 }}
                                transition={{ duration: 0.2, delay: 0.05 }}
                                className="bg-gray-50 rounded-lg border border-gray-200 overflow-hidden"
                            >
                                <SectionHeader section={sections[1]} />
                                <AnimatePresence>
                                    {sections[1].isOpen && (
                                        <motion.div
                                            initial={{ height: 0, opacity: 0 }}
                                            animate={{ height: 'auto', opacity: 1 }}
                                            exit={{ height: 0, opacity: 0 }}
                                            transition={{ duration: 0.2 }}
                                            className="p-4"
                                        >
                                            <textarea
                                                name="description"
                                                value={formData.description || ''}
                                                onChange={handleChange}
                                                className={`textarea w-full focus:ring-2 focus:ring-primary focus:border-primary transition-all ${errors.description ? 'border-red-500' : ''}`}
                                                placeholder="Enter description (optional)"
                                                rows={4}
                                                maxLength={255}
                                                disabled={isSubmitting}
                                            />
                                            {errors.description && (
                                                <span className="text-red-500 text-sm mt-1 block">{errors.description}</span>
                                            )}
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </motion.div>
                        </div>
                    </div>

                    {/* Form Footer */}
                    <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex justify-end gap-3">
                        <button
                            className="btn btn-light border border-gray-300 hover:bg-gray-50 transition-colors"
                            onClick={handleBackClick}
                            disabled={isSubmitting}
                        >
                            Cancel
                        </button>
                        <button
                            className="btn btn-primary hover:bg-primary-dark transition-colors"
                            onClick={handleSubmit}
                            disabled={isSubmitting}
                        >
                            {isSubmitting ? 'Updating...' : 'Update Inventory Item'}
                        </button>
                    </div>
                </div>
            </div>
        </>
    );
};

export default EditInventory;
